CREATE TABLE Clients
(
	ID INT IDENTITY(1,1) CONSTRAINT PK_Clients PRIMARY KEY,
	FullName NVARCHAR(60) NOT NULL,
	Passport NVARCHAR(100) NOT NULL CONSTRAINT UQ_Clients_Passport UNIQUE,
	Adress NVARCHAR(100) NOT NULL,
	PhoneNumber BIGINT NOT NULL CONSTRAINT UQ_Clients_PhoneNumber UNIQUE,
	Comment NVARCHAR(20) NULL
)

CREATE TABLE Deals
(
	ID INT IDENTITY(1,1) CONSTRAINT PK_Deals PRIMARY KEY,
	AmountRepaidDebt MONEY NOT NULL CONSTRAINT DF_Deals_AmountRepaidDebt DEFAULT(0),
	CommissionPercentage MONEY NOT NULL,
	DealDate DATE NOT NULL,
	Payout MONEY NOT NULL,
	RepaymentDate DATE NOT NULL,
	ClientID INT NULL
		CONSTRAINT FK_Deals_Clients
			FOREIGN KEY REFERENCES Clients(ID)
			ON DELETE SET NULL
			ON UPDATE CASCADE,
)

CREATE TABLE Payments
(
	ID INT IDENTITY(1,1) CONSTRAINT PK_Payments PRIMARY KEY,
	Total MONEY NOT NULL,
	PaymentDate DATE NOT NULL,
	DealID INT NULL
		CONSTRAINT FK_Payments_Deals
			FOREIGN KEY REFERENCES Deals(ID)
			ON DELETE SET NULL
			ON UPDATE CASCADE,
)

CREATE TABLE Sales
(
	ID INT IDENTITY(1,1) CONSTRAINT PK_Sales PRIMARY KEY,
	SalePrice MONEY NOT NULL,
	SaleDate DATE NOT NULL
)

CREATE TABLE Items
(
	ID INT IDENTITY(1,1) CONSTRAINT PK_Items PRIMARY KEY,
	ItemType NVARCHAR(60) NOT NULL,
	ItemСondition NVARCHAR(60) NOT NULL,
	ItemPrice MONEY NOT NULL,
	SaleID INT NULL
		CONSTRAINT FK_Items_Sales
			FOREIGN KEY REFERENCES Sales(ID)
			ON DELETE SET NULL
			ON UPDATE CASCADE,
	DealID INT NULL
		CONSTRAINT FK_Items_Deals
			FOREIGN KEY REFERENCES Deals(ID)
			ON DELETE SET NULL
			ON UPDATE CASCADE,
)

CREATE TABLE Materials
(
	ID INT IDENTITY(1,1) CONSTRAINT PK_Materials PRIMARY KEY,
	MaterialName NVARCHAR(60) NOT NULL,
)

CREATE TABLE MaterialLists
(
	ItemID INT NOT NULL
		CONSTRAINT FK_MaterialLists_Items
			FOREIGN KEY REFERENCES Items(ID)
			ON UPDATE CASCADE,
	MaterialID INT NOT NULL
		CONSTRAINT FK_MaterialLists_Materials
			FOREIGN KEY REFERENCES Materials(ID)
			ON UPDATE CASCADE
	PRIMARY KEY (ItemID,MaterialID),

	Weight INT NOT NULL

)